Lexxpavlov\SpellingBundle\Entity\SpellingSecurity:
    type: mappedSuperclass
    uniqueConstraints:
        ip_idx:
            columns: [ ip ]
    indexes:
        last_query_idx:
            columns: [ last_query ]
        banned_until_idx:
            columns: [ banned_until ]
    fields:
        ip:
            type:     string
            length:   45
            column:   ip
        lastQuery:
            type:     datetime
            column:   last_query
        count:
            type:     integer
            column:   count
        errorTime:
            type:     datetime
            column:   error_time
            nullable: true
        bannedUntil:
            type:     datetime
            column:   banned_until
            nullable: true
